export const GET_LIST_INGREDIENTS = 'LIST_INGREDIENTS';
export const LIST_CURRENT_INGREDIENTS = 'LIST_CURRENT_INGREDIENTS';
export const CURRENT_INGREDIENT = 'CURRENT_INGREDIENT';
export const CREATED_ORDER = 'CREATED_ORDER';
export const GET_FEED = 'GET_FEED';
export const GET_FEED_FAILED = 'GET_FEED_FAILED';
export const CHANGE_LIST_CURRENT_INGREDIENTS = 'CHANGE_LIST_CURRENT_INGREDIENTS';
